version: "2"

run:
  timeout: 10m
  tests: false
linters:
  exclusions:
    paths:
      - ^test/
      - ".*test.*.go"
  settings:
    staticcheck:
      checks:
        - 'all'
        - '-ST1005'
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
