name: Continuous Integration

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    needs: vars
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Golang Environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Run Tests
        run: make test

  push_to_registry:
    name: Push docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag l7mp/stunner-gateway-operator:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push l7mp/stunner-gateway-operator:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag l7mp/stunner-gateway-operator:latest
      - name: Push the latest Docker image
        run: docker push l7mp/stunner-gateway-operator:latest

  push_chart:
    name: Push charts to the web
    runs-on: ubuntu-latest
    steps:
      - name: stunner checkout
        uses: actions/checkout@v3
        with:
          path: stunner-gateway-operator
          ref: main
          repository: l7mp/stunner-gateway-operator
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
      - name: l7mp.io checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WEB_PAT_TOKEN }}
          path: l7mp.io
          ref: master
          repository: l7mp/l7mp.io
      - name: stunner-helm checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WEB_PAT_TOKEN }}
          path: stunner-helm
          ref: main
          repository: l7mp/stunner-helm
      - name: Set git config
        run: |
          git config --global user.email "l7mp.info@gmail.com"
          git config --global user.name "BotL7mp"
      - name: Build helm charts
        run: |
          cd stunner-helm/helm
          sed -ri 's/^(\s*)(version\s*:\s*.*\s*$)/\1version: ${{steps.vars.outputs.tag}}/' stunner-gateway-operator/Chart.yaml
          sed -ri 's/^(\s*)(appVersion\s*:\s*.*\s*$)/\1appVersion: ${{steps.vars.outputs.tag}}/' stunner-gateway-operator/Chart.yaml
          sed -ri 's/^(\s*)(        tag\s*:\s*.*\s*$)/\1        tag: ${{steps.vars.outputs.tag}}/' stunner-gateway-operator/values.yaml
          helm package *
      - name: Update l7mp.io
        run: |
          cp stunner-helm/helm/*.tgz l7mp.io/stunner
          helm repo index l7mp.io/stunner/ --url https://l7mp.io/stunner
          cd l7mp.io
          git add .
          git commit -m "Update helm charts from l7mp/stunner-gateway-operator" -m "(triggered by the 'Helm release' github action.)"
          git push origin master
      - name: Update stunner
        run: |
          cd stunner-helm
          rm helm/*.tgz
          git add .
          git commit -m "Update helm chart from l7mp/stunner-gateway-operator" -m "(triggered by the 'Helm release' github action.)"
          git push origin main
