name: Build and Push Docker Image for PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # run_unit_tests:
  #   name: Run unit tests
  #   uses: l7mp/stunner-gateway-operator/.github/workflows/test.yml@main

  push_to_registry:
    name: Push Docker image to DockerHub
    if: github.repository == 'l7mp/stunner-gateway-operator'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            l7mp/stunner-gateway-operator:pr-${{ github.event.pull_request.number }}

      - name: Comment on PR
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.issue.number;
            const comment = `The Docker image for this pull request (#${prNumber}) has been successfully built and pushed to DockerHub as \`docker.io/l7mp/stunner-gateway-operator:pr-${prNumber}\`.`;
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
